logging:
  level:
    com.tracker.backend: DEBUG

---
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/backend
    username: backend_admin
    password: dockerpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
---