logging:
  level:
    com.tracker.backend: INFO

# Cors configuration
backend:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    keycloak: http://localhost:8443
    realm: app
    issuer-uri: ${app.jwt.keycloak}/realms/${app.jwt.realm}
    resource-client-id: frontend-web

# Open API documentation available at http://localhost:8080/budget-tracker-api-ui.html
springdoc:
  api-docs:
    path: /budget-tracker-api-docs
  swagger-ui:
    path: /budget-tracker-api-ui.html
    operations-sorter: method
    tags-sorter: alpha


# Spring configuration
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${app.jwt.issuer-uri}
          jwk-set-uri: ${app.jwt.issuer-uri}/protocol/openid-connect/certs
  #          public-key-location: classpath:keycloak-key.pub

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # possible values: validate | update | create | create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

app:
    jwt:
        issuer-uri: http://keycloak:8443

